name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: echo "y" | .vscode/setup.sh
      - name: Build
        run: |
          mkdir -p "${{ runner.temp }}/decky"
          cli/decky plugin build -t "${{ runner.temp }}/decky"
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: Plugin
          path: "out/Window Switcher.zip"
  release:
    if: startsWith(github.ref, 'refs/heads/main')
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Release
        id: release
        uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: minor
      - name: Download artifacts for release
        uses: actions/download-artifact@v4
        with:
          name: Plugin
      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "Window Switcher.zip"
          tag: ${{ steps.release.outputs.tag_name }}
